/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: ['variant', '&[data-theme=dark]'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        'surface-2': 'var(--raised)',
        raised: 'var(--raised)',
        ink: 'var(--ink)',
        muted: 'var(--muted)',
        faint: 'var(--faint)',
        line: 'var(--line)',
        night: 'var(--night)',
        night2: 'var(--night2)',
        gold: 'var(--gold)',
        green: 'var(--green)',
        'green-soft': 'var(--green-soft)',
        earth: 'var(--earth)',
        red: 'var(--red)',
        blue: 'var(--blue)',
        quiet: 'var(--muted)',
        cream: 'var(--ink)',
        paper: 'var(--surface)',
        input: 'var(--raised)',
        deep: 'var(--raised)',
        'text': 'var(--ink)',
        'green-bg': 'color-mix(in oklab, var(--green) 15%, var(--surface))',
        'red-bg': 'color-mix(in oklab, var(--red) 15%, var(--surface))',
        'gold-bg': 'color-mix(in oklab, var(--gold) 18%, var(--surface))',
        'blue-bg': 'color-mix(in oklab, var(--blue) 15%, var(--surface))',
        'earth-bg': 'color-mix(in oklab, var(--earth) 15%, var(--surface))',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'DM Sans', 'system-ui', 'sans-serif'],
      },
      animation: {
        rise: 'rise .35s cubic-bezier(.16,1,.3,1)',
        sheet: 'sheet .35s cubic-bezier(.16,1,.3,1)',
        float: 'float 3s ease-in-out infinite',
      },
      keyframes: {
        rise: { '0%': { opacity: '0', transform: 'translateY(9px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        sheet: { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        float: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
      },
    },
  },
  plugins: [],
}
